# Generated by Django 4.2.7 on 2023-11-23 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_article_remove_book_author_remove_book_genre_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите категорию новости",
                        max_length=200,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="article",
            name="date",
            field=models.DateTimeField(
                auto_created=True, verbose_name="Дата публикации"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="news.category",
            ),
        ),
    ]
