# Generated by Django 4.2.7 on 2023-12-10 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0006_alter_article_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=15)),
                ("status", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Тэг",
                "verbose_name_plural": "Тэги",
                "ordering": ["title", "status"],
            },
        ),
        migrations.RemoveField(
            model_name="article",
            name="image",
        ),
        migrations.AlterField(
            model_name="article",
            name="date",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата публикации"),
        ),
        migrations.CreateModel(
            name="ShowImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=50)),
                ("image", models.ImageField(upload_to="article_images/")),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="news.article"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                blank=True, to="news.tag", verbose_name="Тэги"
            ),
        ),
    ]
