# Generated by Django 4.2.7 on 2023-12-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0007_tag_remove_article_image_alter_article_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showimage",
            name="title",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
