# Generated by Django 4.2.7 on 2023-12-17 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0009_alter_showimage_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ViewCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_adress", models.GenericIPAddressField()),
                ("view_date", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="счетчик_просмотров",
                        to="news.article",
                    ),
                ),
            ],
            options={
                "ordering": ("-view_date",),
                "indexes": [
                    models.Index(
                        fields=["-view_date"], name="news_viewco_view_da_20d13d_idx"
                    )
                ],
            },
        ),
    ]
