# Generated by Django 4.2.7 on 2023-12-17 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0010_viewcounter"),
    ]

    operations = [
        migrations.RenameField(
            model_name="viewcounter",
            old_name="ip_adress",
            new_name="ip_address",
        ),
        migrations.AlterField(
            model_name="viewcounter",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="views",
                to="news.article",
                verbose_name="Счетчик просмотров",
            ),
        ),
    ]
