# Generated by Django 4.2.7 on 2023-11-24 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"verbose_name": "Аккаунт", "verbose_name_plural": "Аккаунты"},
        ),
        migrations.AlterField(
            model_name="account",
            name="account_image",
            field=models.ImageField(
                default="account_images/default_account.png",
                upload_to="account_images",
                verbose_name="Изображение профиля",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="birthdate",
            field=models.DateField(null=True, verbose_name="Дата рождения"),
        ),
        migrations.AlterField(
            model_name="account",
            name="gender",
            field=models.CharField(
                choices=[("M", "Мужской"), ("Ж", "Женский"), ("Н/Д", "не указано")],
                max_length=20,
                verbose_name="Пол",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="nickname",
            field=models.CharField(max_length=50, verbose_name="Никнэйм"),
        ),
        migrations.AlterField(
            model_name="account",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
