# Generated by Django 4.2.7 on 2023-12-08 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_account_account_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="nickname",
        ),
    ]
