# Generated by Django 4.2.7 on 2023-12-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_account_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="account_image",
            field=models.ImageField(
                default="account_images/default_account.png",
                upload_to="account_images",
                verbose_name="Изображение профиля",
            ),
        ),
    ]
