# Generated by Django 4.2.7 on 2023-12-17 13:53

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_account_account_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_image",
            field=models.ImageField(
                default="account_images/default_account.png",
                upload_to=users.models.Account.folder_path,
                verbose_name="Изображение профиля",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="birthdate",
            field=models.DateField(verbose_name="Дата рождения"),
        ),
    ]
