# Generated by Django 4.2.7 on 2023-12-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_account_account_image_alter_account_birthdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="birthdate",
            field=models.DateField(null=True, verbose_name="Дата рождения"),
        ),
    ]
